import { UserRole } from '../enums/user-role.enum.js';

export enum Permission {
  AdminAnalyticsRead = 'admin.analytics.read',
  AdminAuditLogsRead = 'admin.audit_logs.read',
  AdminDeliveryCreateTtn = 'admin.delivery.create_ttn',
  AdminDesignsRead = 'admin.designs.read',
  AdminDesignsReview = 'admin.designs.review',
  AdminDropsCreate = 'admin.drops.create',
  AdminDropsLaunch = 'admin.drops.launch',
  AdminDropsRead = 'admin.drops.read',
  AdminDropsUpdate = 'admin.drops.update',
  AdminOrdersRead = 'admin.orders.read',
  AdminOrdersUpdate = 'admin.orders.update',
  AdminPayoutsMarkPaid = 'admin.payouts.mark_paid',
  AdminPayoutsRead = 'admin.payouts.read',
  AdminProductionRead = 'admin.production.read',
  AdminProductionUpdate = 'admin.production.update',
  AdminRequestsManage = 'admin.requests.manage',
  AdminRequestsRead = 'admin.requests.read',
  AdminSecondChanceManage = 'admin.second_chance.manage',
  AdminSecondChanceRead = 'admin.second_chance.read',
  AdminUsersRead = 'admin.users.read',
  AdminUsersUpdate = 'admin.users.update',
  DesignerAnalyticsRead = 'designer.analytics.read',
  DesignerApply = 'designer.apply',
  DesignerDesignsCreate = 'designer.designs.create',
  DesignerDesignsRead = 'designer.designs.read',
  DesignerDesignsSubmit = 'designer.designs.submit',
  DesignerDesignsUpdate = 'designer.designs.update',
  DesignerPayoutsRead = 'designer.payouts.read',
  DesignerProfileRead = 'designer.profile.read',
  DesignerProfileUpdate = 'designer.profile.update',
  FilesPrivateRead = 'files.private.read',
  NotificationsRead = 'notifications.read',
  NotificationsUpdate = 'notifications.update',
  OrdersCreate = 'orders.create',
  OrdersRead = 'orders.read',
  OrdersUpdate = 'orders.update',
  ProfileRead = 'profile.read',
  ProfileUpdate = 'profile.update',
  WishlistManage = 'wishlist.manage',
}

export const USER_ROLE_PERMISSIONS: Record<UserRole, readonly Permission[]> = {
  [UserRole.User]: [
    Permission.DesignerApply,
    Permission.NotificationsRead,
    Permission.NotificationsUpdate,
    Permission.OrdersCreate,
    Permission.OrdersRead,
    Permission.OrdersUpdate,
    Permission.ProfileRead,
    Permission.ProfileUpdate,
    Permission.WishlistManage,
  ],
  [UserRole.Designer]: [
    Permission.DesignerAnalyticsRead,
    Permission.DesignerApply,
    Permission.DesignerDesignsCreate,
    Permission.DesignerDesignsRead,
    Permission.DesignerDesignsSubmit,
    Permission.DesignerDesignsUpdate,
    Permission.DesignerPayoutsRead,
    Permission.DesignerProfileRead,
    Permission.DesignerProfileUpdate,
    Permission.NotificationsRead,
    Permission.NotificationsUpdate,
    Permission.OrdersCreate,
    Permission.OrdersRead,
    Permission.OrdersUpdate,
    Permission.ProfileRead,
    Permission.ProfileUpdate,
    Permission.WishlistManage,
  ],
  [UserRole.Admin]: [
    Permission.AdminAnalyticsRead,
    Permission.AdminAuditLogsRead,
    Permission.AdminDeliveryCreateTtn,
    Permission.AdminDesignsRead,
    Permission.AdminDesignsReview,
    Permission.AdminDropsCreate,
    Permission.AdminDropsLaunch,
    Permission.AdminDropsRead,
    Permission.AdminDropsUpdate,
    Permission.AdminOrdersRead,
    Permission.AdminOrdersUpdate,
    Permission.AdminPayoutsMarkPaid,
    Permission.AdminPayoutsRead,
    Permission.AdminProductionRead,
    Permission.AdminProductionUpdate,
    Permission.AdminRequestsManage,
    Permission.AdminRequestsRead,
    Permission.AdminSecondChanceManage,
    Permission.AdminSecondChanceRead,
    Permission.AdminUsersRead,
    Permission.AdminUsersUpdate,
    Permission.FilesPrivateRead,
    Permission.NotificationsRead,
    Permission.NotificationsUpdate,
    Permission.OrdersRead,
    Permission.OrdersUpdate,
    Permission.ProfileRead,
    Permission.ProfileUpdate,
    Permission.WishlistManage,
  ],
};

export function getDefaultPermissionsForRole(role: UserRole): readonly Permission[] {
  return USER_ROLE_PERMISSIONS[role];
}

export function hasPermission(
  role: UserRole,
  permission: Permission,
  extraPermissions: readonly string[] = [],
): boolean {
  return USER_ROLE_PERMISSIONS[role].includes(permission) || extraPermissions.includes(permission);
}
