export enum DropStatus {
  Draft = 'draft',
  Scheduled = 'scheduled',
  Active = 'active',
  ReadyForLaunch = 'ready_for_launch',
  ActiveCollecting = 'active_collecting',
  Guaranteed = 'guaranteed',
  SoldOut = 'sold_out',
  Successful = 'successful',
  Failed = 'failed',
  InProduction = 'in_production',
  ReadyToShip = 'ready_to_ship',
  Shipped = 'shipped',
  Delivered = 'delivered',
  Completed = 'completed',
  SecondChanceWindow = 'second_chance_window',
  ForeverClosed = 'forever_closed',
  Cancelled = 'cancelled',
  Archived = 'archived',
}
